//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PluginDemocracy.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class TranslationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TranslationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PluginDemocracy.Translations.TranslationResources", typeof(TranslationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Community.
        /// </summary>
        internal static string AboutCommunity {
            get {
                return ResourceManager.GetString("AboutCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accounting.
        /// </summary>
        internal static string Accounting {
            get {
                return ResourceManager.GetString("Accounting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Requested.
        /// </summary>
        internal static string ActionRequested {
            get {
                return ResourceManager.GetString("ActionRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A clear statement of what you want the board to do as a result of the petition.
        /// </summary>
        internal static string ActionRequestedDescription {
            get {
                return ResourceManager.GetString("ActionRequestedDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This section helps you add multitple homes quickly so you don&apos;t have to add a home one by one. If you need to, you can add multiple homes and then edit the individual information of each home below. .
        /// </summary>
        internal static string AddHomesAutomaticallyDescription {
            get {
                return ResourceManager.GetString("AddHomesAutomaticallyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select whether you are joining as a home owner or a resident. If joining as a home owner, you will need to specify your ownership percentage. If there are already homeowners registered, the total value of ownership over the house cannot exceed 100%. In communities where the voting power is in home owners, your percentage of ownership over the home will be reflected in equal percentage on your home&apos;s vote on proposals. .
        /// </summary>
        internal static string AreYouJoiningAsAHomeOwnerOrResidentDialogContent {
            get {
                return ResourceManager.GetString("AreYouJoiningAsAHomeOwnerOrResidentDialogContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the body of the Article. This is the actual Article/Law. .
        /// </summary>
        internal static string ArticleBodyUIInputDescription {
            get {
                return ResourceManager.GetString("ArticleBodyUIInputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article&apos;s body.
        /// </summary>
        internal static string ArticleBodyUIInputLabel {
            get {
                return ResourceManager.GetString("ArticleBodyUIInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this is set, the Article will expire and the given date and it will be removed from the constitution.
        /// </summary>
        internal static string ArticleExpirationDateUIInputDescription {
            get {
                return ResourceManager.GetString("ArticleExpirationDateUIInputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article&apos;s expiration date.
        /// </summary>
        internal static string ArticleExpirationDateUIInputLabel {
            get {
                return ResourceManager.GetString("ArticleExpirationDateUIInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is to select the number that the article will take in the constitution. If no number is selected, the Article is added as the newest number in the constitution. If a number is selected and the proposal passes, the Article will have this number and previous Articles with this number or higher will be pushed one number up. .
        /// </summary>
        internal static string ArticleNumberDescription {
            get {
                return ResourceManager.GetString("ArticleNumberDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article Number.
        /// </summary>
        internal static string ArticleNumberLabel {
            get {
                return ResourceManager.GetString("ArticleNumberLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the title of the Article as it will show up on the constitution for this community.
        /// </summary>
        internal static string ArticleTitleUIInputDescription {
            get {
                return ResourceManager.GetString("ArticleTitleUIInputDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article&apos;s Title.
        /// </summary>
        internal static string ArticleTitleUIInputLabel {
            get {
                return ResourceManager.GetString("ArticleTitleUIInputLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is an article that is stored in the constitution. It reflects the rules and regulations that the community follow. They are determine by popular vote in the community. If a number is chosen for the article, it will be placed as that number in the constitution and all the other articles will be pushed one number up. .
        /// </summary>
        internal static string ArticleUIContainerDescription {
            get {
                return ResourceManager.GetString("ArticleUIContainerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constitution Article.
        /// </summary>
        internal static string ArticleUIContainerTitle {
            get {
                return ResourceManager.GetString("ArticleUIContainerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available ownership.
        /// </summary>
        internal static string AvailableOwnership {
            get {
                return ResourceManager.GetString("AvailableOwnership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        internal static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communities.
        /// </summary>
        internal static string Communities {
            get {
                return ResourceManager.GetString("Communities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Community.
        /// </summary>
        internal static string Community {
            get {
                return ResourceManager.GetString("Community", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constitution.
        /// </summary>
        internal static string Constitution {
            get {
                return ResourceManager.GetString("Constitution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country code.
        /// </summary>
        internal static string CountryCode {
            get {
                return ResourceManager.GetString("CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This type of Dictamen creates a new article or law for this community. The article or law specifies behavior by which citizens need to abide by. It outlines the expectations and rules that govern community interactions and ensures that all members understand their responsibilities. .
        /// </summary>
        internal static string CreateArticleDictamenDescription {
            get {
                return ResourceManager.GetString("CreateArticleDictamenDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a New Article for Constitution.
        /// </summary>
        internal static string CreateArticleDictamenTitle {
            get {
                return ResourceManager.GetString("CreateArticleDictamenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a Petition.
        /// </summary>
        internal static string CreatePetition {
            get {
                return ResourceManager.GetString("CreatePetition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A petition is a tool that allows homeowners like you to initiate changes or actions within our community. Whether you want to propose a new rule, request the addition of community amenities, use community funds for a particular project, or call for the removal of a board member, a petition is the process by which you can achieve this. You first create a petition by filling out all the required fields. You can add other authors so they can also edit the petition. Once you are satisfied with the petition, you [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreatePetitionDescription {
            get {
                return ResourceManager.GetString("CreatePetitionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Proposal.
        /// </summary>
        internal static string CreateProposal {
            get {
                return ResourceManager.GetString("CreateProposal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date of birth.
        /// </summary>
        internal static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deadline for response.
        /// </summary>
        internal static string DeadlineForResponse {
            get {
                return ResourceManager.GetString("DeadlineForResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Optional) A suggested or required timeline for when the petition should be reviewed and responded to by the HOA board..
        /// </summary>
        internal static string DeadlineForResponseDescription {
            get {
                return ResourceManager.GetString("DeadlineForResponseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Post.
        /// </summary>
        internal static string DeletePost {
            get {
                return ResourceManager.GetString("DeletePost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Once deleted it cannot be undone.
        /// </summary>
        internal static string DeletePostCannotBeUndone {
            get {
                return ResourceManager.GetString("DeletePostCannotBeUndone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        internal static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ownership percentage must be between 1 and 100 and can&apos;t be bigger that what is available..
        /// </summary>
        internal static string ErrorMessageJoinHomeWrongPercentage {
            get {
                return ResourceManager.GetString("ErrorMessageJoinHomeWrongPercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feed.
        /// </summary>
        internal static string Feed {
            get {
                return ResourceManager.GetString("Feed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        internal static string ForgotPassword_ {
            get {
                return ResourceManager.GetString("ForgotPassword?", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        internal static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home owner.
        /// </summary>
        internal static string HomeOwner {
            get {
                return ResourceManager.GetString("HomeOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home owners.
        /// </summary>
        internal static string HomeOwners {
            get {
                return ResourceManager.GetString("HomeOwners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homes.
        /// </summary>
        internal static string Homes {
            get {
                return ResourceManager.GetString("Homes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homes&apos;s ending address number.
        /// </summary>
        internal static string HomesEndingNumber {
            get {
                return ResourceManager.GetString("HomesEndingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Homes&apos; starting address number.
        /// </summary>
        internal static string HomesStartingNumber {
            get {
                return ResourceManager.GetString("HomesStartingNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal address.
        /// </summary>
        internal static string InternalAddress {
            get {
                return ResourceManager.GetString("InternalAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join.
        /// </summary>
        internal static string Join {
            get {
                return ResourceManager.GetString("Join", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join a Home.
        /// </summary>
        internal static string JoinAHome {
            get {
                return ResourceManager.GetString("JoinAHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join an existing community.
        /// </summary>
        internal static string JoinAnExistingCommunity {
            get {
                return ResourceManager.GetString("JoinAnExistingCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join a community.
        /// </summary>
        internal static string JoinCommunity {
            get {
                return ResourceManager.GetString("JoinCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        internal static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log out.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name.
        /// </summary>
        internal static string MiddleName {
            get {
                return ResourceManager.GetString("MiddleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input New Password.
        /// </summary>
        internal static string NewPasswordTitle {
            get {
                return ResourceManager.GetString("NewPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notifications.
        /// </summary>
        internal static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Official currency.
        /// </summary>
        internal static string OfficialCurrency {
            get {
                return ResourceManager.GetString("OfficialCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        internal static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        internal static string Percentage {
            get {
                return ResourceManager.GetString("Percentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A detailed description of the issue, including why it is important and what changes or actions are being requested..
        /// </summary>
        internal static string PetitionDescription {
            get {
                return ResourceManager.GetString("PetitionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A clear and concise title that summarizes the purpose of the petition.
        /// </summary>
        internal static string PetitionTitle {
            get {
                return ResourceManager.GetString("PetitionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your email for full functionality.
        /// </summary>
        internal static string PleaseConfirmEmailForFullFunctionality {
            get {
                return ResourceManager.GetString("PleaseConfirmEmailForFullFunctionality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a file.
        /// </summary>
        internal static string PleaseSelectAFile {
            get {
                return ResourceManager.GetString("PleaseSelectAFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin Democracy.
        /// </summary>
        internal static string PluginDemocracy {
            get {
                return ResourceManager.GetString("PluginDemocracy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Primary language and culture.
        /// </summary>
        internal static string PrimaryLanguageAndCulture {
            get {
                return ResourceManager.GetString("PrimaryLanguageAndCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects.
        /// </summary>
        internal static string Projects {
            get {
                return ResourceManager.GetString("Projects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposals.
        /// </summary>
        internal static string Proposals {
            get {
                return ResourceManager.GetString("Proposals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read.
        /// </summary>
        internal static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Red Flags.
        /// </summary>
        internal static string RedFlags {
            get {
                return ResourceManager.GetString("RedFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register a new community.
        /// </summary>
        internal static string RegisterANewCommunity {
            get {
                return ResourceManager.GetString("RegisterANewCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register a community.
        /// </summary>
        internal static string RegisterCommunity {
            get {
                return ResourceManager.GetString("RegisterCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        internal static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resident.
        /// </summary>
        internal static string Resident {
            get {
                return ResourceManager.GetString("Resident", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residents.
        /// </summary>
        internal static string Residents {
            get {
                return ResourceManager.GetString("Residents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second last name.
        /// </summary>
        internal static string SecondLastName {
            get {
                return ResourceManager.GetString("SecondLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select all official languages.
        /// </summary>
        internal static string SelectAllOfficialLanguages {
            get {
                return ResourceManager.GetString("SelectAllOfficialLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an existing community from the dropdown menu.
        /// </summary>
        internal static string SelectCommunityFromDropDown {
            get {
                return ResourceManager.GetString("SelectCommunityFromDropDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select culture.
        /// </summary>
        internal static string SelectCulture {
            get {
                return ResourceManager.GetString("SelectCulture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is the list of homes for this community. Please select which home you belong to as either a resident or a homeowner. Select the appropiate option. After selecting, and posting this form, a request will be sent. Your request will be approved depending on your community&apos;s bylaws. This is done to prevent individuals from claiming they are a part of the community when they are not. Community members can change their community&apos;s member verification process by making a proposal and passing it. If your commun [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SelectHomeDescriptionInJoinCommunity {
            get {
                return ResourceManager.GetString("SelectHomeDescriptionInJoinCommunity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Password Reset Link.
        /// </summary>
        internal static string SendPasswordResetLink {
            get {
                return ResourceManager.GetString("SendPasswordResetLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Request.
        /// </summary>
        internal static string SendRequest {
            get {
                return ResourceManager.GetString("SendRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign up.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanish.
        /// </summary>
        internal static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supporting Arguments.
        /// </summary>
        internal static string SupportingArguments {
            get {
                return ResourceManager.GetString("SupportingArguments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points that support the petition&apos;s request, including any relevant facts, data, or testimonials..
        /// </summary>
        internal static string SupportingArgumentsDescription {
            get {
                return ResourceManager.GetString("SupportingArgumentsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supporting Documents.
        /// </summary>
        internal static string SupportingDocuments {
            get {
                return ResourceManager.GetString("SupportingDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string SupportingDocumentsDescription {
            get {
                return ResourceManager.GetString("SupportingDocumentsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Account Information.
        /// </summary>
        internal static string UpdateAccountInformation {
            get {
                return ResourceManager.GetString("UpdateAccountInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Profile Picture.
        /// </summary>
        internal static string UpdateProfilePicture {
            get {
                return ResourceManager.GetString("UpdateProfilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have not joined any communities. Join an existing community or register a new community. .
        /// </summary>
        internal static string YouHaveNoCommunities {
            get {
                return ResourceManager.GetString("YouHaveNoCommunities", resourceCulture);
            }
        }
    }
}
