//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PluginDemocracy.API.Translations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TranslationResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TranslationResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PluginDemocracy.API.Translations.TranslationResources", typeof(TranslationResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account updated successfully.
        /// </summary>
        public static string AccountUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("AccountUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your inbox to confirm your email.
        /// </summary>
        public static string ConfirmEmailCheckInbox {
            get {
                return ResourceManager.GetString("ConfirmEmailCheckInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Email.
        /// </summary>
        public static string ConfirmEmailLink {
            get {
                return ResourceManager.GetString("ConfirmEmailLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for signing up to Plugin Democracy. A new society awaits your input..
        /// </summary>
        public static string ConfirmEmailP1 {
            get {
                return ResourceManager.GetString("ConfirmEmailP1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your email by clicking on the following link:.
        /// </summary>
        public static string ConfirmEmailP2 {
            get {
                return ResourceManager.GetString("ConfirmEmailP2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm your email.
        /// </summary>
        public static string ConfirmEmailTitle {
            get {
                return ResourceManager.GetString("ConfirmEmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Culture updated successfully .
        /// </summary>
        public static string CultureUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("CultureUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user with the given email was found.
        /// </summary>
        public static string EmailNotFound {
            get {
                return ResourceManager.GetString("EmailNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email address! We&apos;re thrilled to have you on board. 
        ///
        ///You&apos;ve taken an important step in activating your accoung, and now you can help mold the communities in which you live. This is a non-profit ongoing project. If you find any issues with the software or you need features to better serve your community, please take the initiative to let us know. This is one way you can help our communities be more democratic. 
        ///
        ///Sincerely, 
        ///
        ///The Plugin Democracy Team .
        /// </summary>
        public static string EmailOutEmailConfirmedBody {
            get {
                return ResourceManager.GetString("EmailOutEmailConfirmedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address Confirmed - Welcome!.
        /// </summary>
        public static string EmailOutEmailConfirmedTitle {
            get {
                return ResourceManager.GetString("EmailOutEmailConfirmedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token does not match and the email address cannot be confirmed.
        /// </summary>
        public static string EmailTokenNoMatchBody {
            get {
                return ResourceManager.GetString("EmailTokenNoMatchBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The token does not match.
        /// </summary>
        public static string EmailTokenNoMatchTitle {
            get {
                return ResourceManager.GetString("EmailTokenNoMatchTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password has been successfully set.
        /// </summary>
        public static string NewPasswordSuccess {
            get {
                return ResourceManager.GetString("NewPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New user created.
        /// </summary>
        public static string NewUserCreated {
            get {
                return ResourceManager.GetString("NewUserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong password.
        /// </summary>
        public static string PasswordCantBeEmpty {
            get {
                return ResourceManager.GetString("PasswordCantBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password does not match.
        /// </summary>
        public static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile picture updated successfully.
        /// </summary>
        public static string ProfilePictureUpdated {
            get {
                return ResourceManager.GetString("ProfilePictureUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow this link to reset your password:.
        /// </summary>
        public static string ResetPasswordEmailBody {
            get {
                return ResourceManager.GetString("ResetPasswordEmailBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If there is an account with the specified email address, a reset password link has been sent to the inbox. .
        /// </summary>
        public static string ResetPasswordEmailSentBody {
            get {
                return ResourceManager.GetString("ResetPasswordEmailSentBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password link sent to email address.
        /// </summary>
        public static string ResetPasswordEmailSentTitle {
            get {
                return ResourceManager.GetString("ResetPasswordEmailSentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password for Plugin Democracy.
        /// </summary>
        public static string ResetPasswordEmailSubject {
            get {
                return ResourceManager.GetString("ResetPasswordEmailSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your login password for Plugin Democracy has been successfully updated.
        /// </summary>
        public static string SuccessfullyUpdatedPasswordBody {
            get {
                return ResourceManager.GetString("SuccessfullyUpdatedPasswordBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been updated.
        /// </summary>
        public static string SuccessfullyUpdatedPasswordTitle {
            get {
                return ResourceManager.GetString("SuccessfullyUpdatedPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create new user.
        /// </summary>
        public static string UnableToCreateNewUser {
            get {
                return ResourceManager.GetString("UnableToCreateNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user was not found in the database when trying to confirm the Email address..
        /// </summary>
        public static string UserNotFoundBody {
            get {
                return ResourceManager.GetString("UserNotFoundBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have logged in.
        /// </summary>
        public static string YouHaveLoggedIn {
            get {
                return ResourceManager.GetString("YouHaveLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Email Has Been Confirmed.
        /// </summary>
        public static string YourEmailHasBeenConfirmed {
            get {
                return ResourceManager.GetString("YourEmailHasBeenConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email address! We&apos;re thrilled to have you on board..
        /// </summary>
        public static string YourEmailHasBeenConfirmedBody {
            get {
                return ResourceManager.GetString("YourEmailHasBeenConfirmedBody", resourceCulture);
            }
        }
    }
}
